import json
import re
import sqlite3
from click.testing import CliRunner
from lib.steps.start import cli, _generate_session_id
from lib.db import init_db, AgentState


def test_init_creates_session_row(tmp_db, sample_sources_yaml):
    init_db(tmp_db)
    runner = CliRunner()
    result = runner.invoke(cli, [
        "--db", tmp_db,
        "--sources", sample_sources_yaml,
        "--session", "sess-X",
    ])
    assert result.exit_code == 0, result.output
    assert "sess-X" in result.output
    with sqlite3.connect(tmp_db) as conn:
        rec = AgentState.get_by_session_and_step(conn, "sess-X", "start")
    assert rec is not None
    data = json.loads(rec.state_data)
    assert data["session_id"] == "sess-X"
    assert "example_rss" in data["sources"]


def test_init_autogenerates_session_id(tmp_db, sample_sources_yaml):
    init_db(tmp_db)
    runner = CliRunner()
    result = runner.invoke(cli, ["--db", tmp_db, "--sources", sample_sources_yaml])
    assert result.exit_code == 0, result.output
    with sqlite3.connect(tmp_db) as conn:
        sessions = AgentState.list_sessions(conn, n_records=5)
    assert len(sessions) == 1
    # autogenerated id is a full timestamp date-hh-mm-ss, never a bare date
    assert re.fullmatch(r"\d{4}-\d{2}-\d{2}-\d{2}-\d{2}-\d{2}", sessions[0]), sessions[0]


def test_generate_session_id_is_timestamped():
    """The generated id must be YYYY-MM-DD-HH-MM-SS, not a bare date."""
    sid = _generate_session_id()
    assert re.fullmatch(r"\d{4}-\d{2}-\d{2}-\d{2}-\d{2}-\d{2}", sid), sid


def test_bare_date_session_rejected_for_new_session(tmp_db, sample_sources_yaml):
    """Refuse to CREATE a new session whose id is a bare date (collision footgun)."""
    init_db(tmp_db)
    runner = CliRunner()
    result = runner.invoke(cli, [
        "--db", tmp_db, "--sources", sample_sources_yaml, "--session", "2026-06-29",
    ])
    assert result.exit_code != 0, result.output
    assert "bare-date" in result.output.lower() or "bare date" in result.output.lower()
    # nothing should have been created
    with sqlite3.connect(tmp_db) as conn:
        assert AgentState.list_sessions(conn, n_records=5) == []


def test_bare_date_session_allowed_when_already_exists(tmp_db, sample_sources_yaml):
    """A pre-existing bare-date session may still be reused explicitly (legacy data)."""
    init_db(tmp_db)
    # seed a legacy bare-date session directly
    from lib.state import NewsletterAgentState
    NewsletterAgentState(
        session_id="2026-06-29", db_path=tmp_db, sources_file=sample_sources_yaml,
        sources={"example_rss": {"type": "rss"}},
    ).save_checkpoint("start")
    runner = CliRunner()
    result = runner.invoke(cli, [
        "--db", tmp_db, "--sources", sample_sources_yaml, "--session", "2026-06-29",
    ])
    assert result.exit_code == 0, result.output
    assert "2026-06-29" in result.output


def test_custom_non_date_session_id_still_allowed(tmp_db, sample_sources_yaml):
    """Explicit non-date ids (e.g. 'sess-X') remain valid for new sessions."""
    init_db(tmp_db)
    runner = CliRunner()
    result = runner.invoke(cli, [
        "--db", tmp_db, "--sources", sample_sources_yaml, "--session", "sess-X",
    ])
    assert result.exit_code == 0, result.output
    assert "sess-X" in result.output


def test_init_dry_run_summary_lists_enabled_sources(tmp_db, sample_sources_yaml):
    init_db(tmp_db)
    runner = CliRunner()
    result = runner.invoke(cli, [
        "--db", tmp_db, "--sources", sample_sources_yaml, "--session", "s2",
    ])
    assert "example_rss" in result.output
    # example_html is disabled — should still appear but marked
    assert "example_html" in result.output


def test_init_fails_cleanly_on_missing_sources_file(tmp_db):
    init_db(tmp_db)
    runner = CliRunner()
    result = runner.invoke(cli, [
        "--db", tmp_db, "--sources", "/nonexistent.yaml", "--session", "s3",
    ])
    assert result.exit_code != 0
    assert "sources" in result.output.lower()
