"""news:init — create a new session and validate sources.

CLI entry: python -m lib.steps.init --db PATH --sources sources.yaml [--session SID]
"""
from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

import click
import yaml

from lib.db import init_db
from lib.state import NewsletterAgentState


def _generate_session_id() -> str:
    return datetime.now().strftime("%Y-%m-%d-%H%M%S")


def _load_sources(path: str) -> dict:
    p = Path(path)
    if not p.exists():
        raise click.ClickException(f"sources file not found: {path}")
    with p.open() as f:
        data = yaml.safe_load(f) or {}
    if not isinstance(data, dict):
        raise click.ClickException(f"sources file must be a YAML mapping: {path}")
    sources = data.get("sources", data)
    if not isinstance(sources, dict) or not sources:
        raise click.ClickException(f"no sources defined in {path}")
    return sources


@click.command()
@click.option("--db", "db_path", default="newsletter_agent.db",
              help="Path to SQLite database")
@click.option("--sources", "sources_path", default="sources.yaml",
              help="Path to sources.yaml")
@click.option("--session", "session_id", default=None,
              help="Session ID (autogenerated if omitted)")
def cli(db_path: str, sources_path: str, session_id: str | None) -> None:
    """Create a new newsletter session."""
    init_db(db_path)

    sources = _load_sources(sources_path)

    sid = session_id or _generate_session_id()
    state = NewsletterAgentState(
        session_id=sid,
        db_path=db_path,
        sources_file=sources_path,
        sources=sources,
    )
    state.start_step("init")
    state.complete_step("init", message=f"loaded {len(sources)} sources")
    state.save_checkpoint("init")

    click.echo(f"Session created: {sid}")
    click.echo(f"Database: {db_path}")
    click.echo(f"Sources file: {sources_path}")
    click.echo(f"Sources ({len(sources)}):")
    for name, cfg in sources.items():
        enabled = cfg.get("enabled", True) if isinstance(cfg, dict) else True
        marker = "ENABLED " if enabled else "disabled"
        stype = cfg.get("type", "?") if isinstance(cfg, dict) else "?"
        click.echo(f"  [{marker}] {name} ({stype})")
    click.echo(f"Workflow: {len(state.steps)} steps registered.")
    click.echo("Next: /news:gather")


if __name__ == "__main__":  # pragma: no cover
    sys.exit(cli())
