"""newsagent:pipeline — non-interactive newsletter orchestrator (cron / CI).

Sequences all 13 pipeline steps in order, supports resume/from/only flags,
and forwards engine overrides to the appropriate steps. Use this entry point
when you cannot drive parent-Claude Agent dispatch (cron, CI, headless
scripts). Requires --engine to avoid the subagent engine (which calls
claude -p and is not covered by the Max plan).

For interactive use from a parent Claude Code session, invoke /newsagent:pipeline
(the SKILL at skills/pipeline/SKILL.md) instead — that drives the Agent-dispatch
pattern across all LLM steps without using claude -p.

CLI: python -m lib.steps.pipeline [--db ...] [--session SID] [--sources sources.yaml]
         [--from STEP] [--only STEP] [--resume SID]
         [--max-edits N] [--parallelism N] [--engine ENGINE]
         [--no-email] [--no-summary]
"""
from __future__ import annotations

import sys

import click

from lib.state import NewsletterAgentState, WORKFLOW_STEPS

# ---------------------------------------------------------------------------
# Step CLI registry
# ---------------------------------------------------------------------------

from lib.steps import start as step_start
from lib.steps import gather
from lib.steps import filter as step_filter
from lib.steps import download
from lib.steps import dedupe
from lib.steps import summarize
from lib.steps import crossdedupe
from lib.steps import rate
from lib.steps import cluster
from lib.steps import select
from lib.steps import draft
from lib.steps import rewrite
from lib.steps import send

_STEP_CLIS: dict = {
    "start": step_start.cli,
    "gather": gather.cli,
    "filter": step_filter.cli,
    "download": download.cli,
    "dedupe": dedupe.cli,
    "summarize": summarize.cli,
    "crossdedupe": crossdedupe.cli,
    "rate": rate.cli,
    "cluster": cluster.cli,
    "select": select.cli,
    "draft": draft.cli,
    "rewrite": rewrite.cli,
    "send": send.cli,
}

_STEP_IDS: list[str] = [step_id for step_id, *_ in WORKFLOW_STEPS]

# Steps that accept --engine
_ENGINE_STEPS = frozenset({"filter", "summarize", "crossdedupe", "rate", "cluster", "select", "draft", "rewrite"})


# ---------------------------------------------------------------------------
# Arg builder
# ---------------------------------------------------------------------------

def _build_args(
    step_id: str,
    session_id: str,
    db_path: str,
    sources_path: str,
    max_edits: int,
    parallelism: int,
    engine: str | None,
    no_email: bool,
    cached_pages: bool = False,
) -> list[str]:
    args = ["--db", db_path]
    if step_id == "start":
        args.extend(["--sources", sources_path, "--session", session_id])
    else:
        args.extend(["--session", session_id])
    if engine and step_id in _ENGINE_STEPS:
        args.extend(["--engine", engine])
    if step_id in ("draft", "rewrite"):
        args.extend(["--max-edits", str(max_edits)])
    if step_id == "draft":
        args.extend(["--parallelism", str(parallelism)])
    if no_email and step_id in ("rewrite", "send"):
        args.append("--no-email")
    if cached_pages and step_id == "gather":
        args.append("--cached-pages")
    return args


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

@click.command()
@click.option("--db", "db_path", default="newsletter_agent.db",
              help="Path to SQLite database")
@click.option("--session", "session_id", default=None,
              help="Session ID to use (autogenerated if start is in plan)")
@click.option("--new", "new_session", is_flag=True,
              help="Force creation of a new session (autogenerate session id)")
@click.option("--sources", "sources_path", default="sources.yaml",
              help="Path to sources.yaml (used by start step)")
@click.option("--resume", "resume_sid", default=None,
              help="Resume an existing session from its first incomplete step")
@click.option("--from", "from_step", default=None,
              help="Start from this step (and all subsequent steps)")
@click.option("--only", "only_step", default=None,
              help="Run only this single step")
@click.option("--max-edits", default=2, type=int,
              help="Max critic-optimizer iterations for draft/rewrite (default 2)")
@click.option("--parallelism", default=4, type=int,
              help="Parallel section drafters for draft step (default 4)")
@click.option("--engine", default=None,
              help="Override LLM engine for all prompt steps")
@click.option("--no-email", "no_email", is_flag=True,
              help="Skip the Gmail send at the end of rewrite and send "
                   "(email is on by default; requires GMAIL_USER/GMAIL_PASSWORD)")
@click.option("--no-summary", "no_summary", is_flag=True,
              help="Skip writing runs/<SID>/summary.md")
@click.option("--cached-pages", "cached_pages", is_flag=True,
              help="Read html sources from runs/<SID>/pages/ during gather "
                   "(rss/rest still fetched live). Use after dropping a manual "
                   "landing page to resume a halted gather.")
def cli(
    db_path: str,
    session_id: str | None,
    new_session: bool,
    sources_path: str,
    resume_sid: str | None,
    from_step: str | None,
    only_step: str | None,
    max_edits: int,
    parallelism: int,
    engine: str | None,
    no_email: bool,
    no_summary: bool,
    cached_pages: bool,
) -> None:
    """Non-interactive newsletter orchestrator (cron / CI). Sequences all 13 pipeline steps."""

    # ---- Resolve session ----
    if resume_sid:
        session_id = resume_sid
    elif new_session or session_id is None:
        # start step will create the session; we autogenerate the id here
        # so we can pass it to start and use it for subsequent steps.
        session_id = None  # will be set below when start is in the plan

    # ---- Determine step plan ----
    if only_step:
        if only_step not in _STEP_IDS:
            raise click.ClickException(f"Unknown step: {only_step}")
        plan = [only_step]
    elif from_step:
        if from_step not in _STEP_IDS:
            raise click.ClickException(f"Unknown step: {from_step}")
        plan = _STEP_IDS[_STEP_IDS.index(from_step):]
    elif resume_sid:
        state = NewsletterAgentState(
            session_id=resume_sid, db_path=db_path
        ).load_latest_from_db()
        if state is None:
            raise click.ClickException(f"No state for session {resume_sid}")
        current = state.get_current_step()
        if current is None:
            click.echo("All steps complete.")
            return
        plan = _STEP_IDS[_STEP_IDS.index(current):]
    else:
        plan = list(_STEP_IDS)

    # ---- Ensure we have a session id ----
    if session_id is None:
        if plan[0] == "start":
            # Autogenerate now so all subsequent steps use the same id.
            # Shared helper guarantees a timestamped (never bare-date) id.
            from lib.steps.start import _generate_session_id
            session_id = _generate_session_id()
        else:
            raise click.ClickException(
                "Must provide --session or --resume, or include the start step"
            )

    # ---- Run each step ----
    for step_id in plan:
        args = _build_args(
            step_id, session_id, db_path, sources_path,
            max_edits, parallelism, engine, no_email,
            cached_pages=cached_pages,
        )
        click.echo(f"\n=== {step_id} ===")
        try:
            _STEP_CLIS[step_id].main(args, standalone_mode=False)
        except SystemExit as exc:
            if exc.code not in (None, 0):
                raise click.ClickException(
                    f"Step {step_id} failed with exit code {exc.code}"
                )
        except Exception as exc:
            raise click.ClickException(f"Step {step_id} failed: {exc}")

    # ---- Summary ----
    if not no_summary and session_id:
        from lib.run_summary import write_summary
        path = write_summary(session_id, db_path=db_path)
        click.echo(f"\nSummary written to {path}")


if __name__ == "__main__":  # pragma: no cover
    sys.exit(cli())
