"""newsagent:start — create a new session and validate sources.

CLI entry: python -m lib.steps.start --db PATH --sources sources.yaml [--session SID]
"""
from __future__ import annotations

import re
import sqlite3
import sys
from datetime import datetime
from pathlib import Path

import click
import yaml

from lib.db import init_db, AgentState
from lib.state import NewsletterAgentState

# A session id that is *only* a calendar date (e.g. "2026-06-29"). Such ids
# collide across multiple runs on the same day, silently reusing/overwriting an
# earlier run's cached articles and summaries. New sessions must be timestamped.
_BARE_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def _generate_session_id() -> str:
    """A fresh, collision-free id: date-hh-mm-ss (unique to the second)."""
    return datetime.now().strftime("%Y-%m-%d-%H-%M-%S")


def _session_exists(db_path: str, session_id: str) -> bool:
    with sqlite3.connect(db_path) as conn:
        return session_id in set(AgentState.list_sessions(conn, n_records=10_000))


def _load_sources(path: str) -> dict:
    p = Path(path)
    if not p.exists():
        raise click.ClickException(f"sources file not found: {path}")
    with p.open() as f:
        data = yaml.safe_load(f) or {}
    if not isinstance(data, dict):
        raise click.ClickException(f"sources file must be a YAML mapping: {path}")
    sources = data.get("sources", data)
    if not isinstance(sources, dict) or not sources:
        raise click.ClickException(f"no sources defined in {path}")
    return sources


@click.command()
@click.option("--db", "db_path", default="newsletter_agent.db",
              help="Path to SQLite database")
@click.option("--sources", "sources_path", default="sources.yaml",
              help="Path to sources.yaml")
@click.option("--session", "session_id", default=None,
              help="Session ID (autogenerated as YYYY-MM-DD-HH-MM-SS if omitted; "
                   "a bare calendar date is rejected for new sessions)")
def cli(db_path: str, sources_path: str, session_id: str | None) -> None:
    """Create a new newsletter session."""
    init_db(db_path)

    # Guard against creating a NEW session keyed only by a calendar date.
    # Reusing an already-existing bare-date session (legacy data) is allowed.
    if (session_id is not None
            and _BARE_DATE_RE.match(session_id)
            and not _session_exists(db_path, session_id)):
        raise click.ClickException(
            f"Refusing to create a new session with the bare-date id {session_id!r}. "
            "Bare-date ids collide across same-day runs (a later run silently reuses "
            "the earlier run's cached articles/summaries). Omit --session to "
            "autogenerate a YYYY-MM-DD-HH-MM-SS id, or pass an existing session id "
            "(e.g. via --resume) to reuse it deliberately."
        )

    sources = _load_sources(sources_path)

    sid = session_id or _generate_session_id()
    state = NewsletterAgentState(
        session_id=sid,
        db_path=db_path,
        sources_file=sources_path,
        sources=sources,
    )
    state.start_step("start")
    state.complete_step("start", message=f"loaded {len(sources)} sources")
    state.save_checkpoint("start")

    click.echo(f"Session created: {sid}")
    click.echo(f"Database: {db_path}")
    click.echo(f"Sources file: {sources_path}")
    click.echo(f"Sources ({len(sources)}):")
    for name, cfg in sources.items():
        enabled = cfg.get("enabled", True) if isinstance(cfg, dict) else True
        marker = "ENABLED " if enabled else "disabled"
        stype = cfg.get("type", "?") if isinstance(cfg, dict) else "?"
        click.echo(f"  [{marker}] {name} ({stype})")
    click.echo(f"Workflow: {len(state.steps)} steps registered.")
    click.echo("Next: /newsagent:gather")


if __name__ == "__main__":  # pragma: no cover
    sys.exit(cli())
